
name: test

on: [workflow_dispatch]

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install platform and libraries
        run: |
          arduino-cli config init
          arduino-cli config set library.enable_unsafe_install true
          arduino-cli core update-index
          arduino-cli core install arduino:avr
          arduino-cli lib install --git-url https://github.com/etherkit/MorseArduino.git
          arduino-cli lib install --git-url https://github.com/schinken/SimpleTimer.git

      - name: Compile Sketch
        run: arduino-cli compile --fqbn arduino:avr:uno -e ./HalloDinge

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "HalloDinge/build/arduino.avr.uno/*"
          tag: v0.1.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
